// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQdLMgW1C5VCszjRSq52FGh_hV8lGKr-4',
    appId: '1:321196714455:web:YOUR_WEB_APP_ID',
    messagingSenderId: '321196714455',
    projectId: 'e-ticket-ff181',
    authDomain: 'e-ticket-ff181.firebaseapp.com',
    storageBucket: 'e-ticket-ff181.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQdLMgW1C5VCszjRSq52FGh_hV8lGKr-4',
    appId: '1:321196714455:android:3ff8051f1ee87965fb4392',
    messagingSenderId: '321196714455',
    projectId: 'e-ticket-ff181',
    storageBucket: 'e-ticket-ff181.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbDuyuLM_cdiTav34rvdykoEMs0qKMhP4',
    appId: '1:774845116609:ios:4a063baf2e30a984bc6440',
    messagingSenderId: '774845116609',
    projectId: 'e-ticket-2e8d0',
    databaseURL:
        'https://e-ticket-2e8d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-ticket-2e8d0.firebasestorage.app',
    iosBundleId: 'com.uvexpress.eticket.uvexpressEticket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbDuyuLM_cdiTav34rvdykoEMs0qKMhP4',
    appId: '1:774845116609:ios:4a063baf2e30a984bc6440',
    messagingSenderId: '774845116609',
    projectId: 'e-ticket-2e8d0',
    databaseURL:
        'https://e-ticket-2e8d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-ticket-2e8d0.firebasestorage.app',
    iosBundleId: 'com.uvexpress.eticket.uvexpressEticket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVi4bFIlWzIW2H1Gs_1mxnhjQZ0XPXyFM',
    appId: '1:774845116609:web:44bbfe42f4ae8ecabc6440',
    messagingSenderId: '774845116609',
    projectId: 'e-ticket-2e8d0',
    authDomain: 'e-ticket-2e8d0.firebaseapp.com',
    databaseURL:
        'https://e-ticket-2e8d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-ticket-2e8d0.firebasestorage.app',
    measurementId: 'G-YX8RBWK5RX',
  );
}
